### ISSUE TITLE
mobx 文档已经有人翻译？

### ISSUE THREAD

**Issue by rccoder** [suprise/mobx-cn#15]
这个文档和 mobx 官方推荐的 [http://cn.mobx.js.org/](http://cn.mobx.js.org/) 有什么区别？

**Comment by BlackGanglion** [comment]
应该是同时期两波人干了相同的事，我们并没有想到提 PR 给官方文档做一个中文文档入口，晚了一步

**Comment by rccoder** [comment]
🤓原来如此

**Comment by suprise** [comment]
@rccoder 纯属撞梗，不过两边翻译的文风会有一些差别。如果觉得看某一端翻译有疑问，可以交换着看~

**Comment by tiann** [comment]
这个文档已经不如另外一个文档新了，建议后来者查看新的官方文档。

比如decorators这一章：
官方：http://cn.mobx.js.org/best/decorators.html
本仓库：https://suprise.github.io/mobx-cn/best/decorators.html

**Comment by jiangwenyang** [comment]
虽然这个文档不如性官方文档新，但是我感觉这个文档翻译得好很多。。。官方文档有点”机翻“的既视感
